import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from './context/AppContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <title>Prompt Engineering</title>
      </head>
      <body>
        <AppProvider>
          <div className="container mx-auto p-4">
            {children}
          </div>
        </AppProvider>
      </body>
    </html>
  );
};

export default RootLayout;
